### ISSUE TITLE
Problem on github actions documentation

### ISSUE THREAD

**Issue by filipemelo** [ZupIT/horusec-docs#129]
**What happened**:
https://horusec.io/docs/pt-br/cli/installation/ if you try to add the github actions on your project as is in the page, the github says there is an error on  the line "with: # Necessário quando habilitado o autores de commit".

**How to reproduce it (as minimally and precisely as possible)**:
Add a github actions as is in the page.

```
name: SecurityPipeline

on: [push]

jobs:
  horusec-security:
    name: horusec-security
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
        with: # Necessário quando habilitado o autores de commit
          fetch-depth: 0
    - name: Running Horusec Security
      run: |
        curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
        horusec start -p="./" -e="true"
```

**Anything else we need to know?**:
Is the first time I used github actions, so maybe i am doing something wrong, if this is the case, we should explain better how to add this at github actions.

**Environment**:
Used the provideded enviroment on githubusercontent and with -s latest.
